
namespace BookLibrary.Entities
{
	public enum BookSection
	{
		FICTION, HOBBY, SELF_DEVELOPMENT, ECONOMY,
		SCIENCE, ART, FOREIGN_LANGUAGES, PROGRAMMING,
		TECHNOLOGIES, COOKERY, TRAVELS, DOCUMENTARY,
		HISTORY, OTHER
	}
}
